# Generated by Django 5.1.3 on 2024-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=100)),
                ('tamilname', models.CharField(max_length=10)),
                ('chapter', models.CharField(max_length=100)),
                ('versecount', models.CharField(max_length=100)),
                ('verse', models.CharField(max_length=100)),
                ('kjv', models.CharField(max_length=100)),
            ],
        ),
    ]
