# Generated by Django 5.1.3 on 2024-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamilbible', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongEntry',
            new_name='BilbleDb',
        ),
    ]
